
before_install:
  - cd Example
  - carthage update
language: objective-c
osx_image: xcode10.2
xcode_sdk: iphonesimulator11.0
# Continuous Integration Script
#   fastlane scan - runs the application tests
script:
- fastlane scan
after_success:
    - gem install jazzy
    - fastlane jazzy
  deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: docs
  on:
    branch: master