language: objective-c
osx_image: xcode10
env:
- DESTINATION="OS=11.0",name="iPhone 7" SCHEME="$SCHEME" SDK="$SDK"
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - git submodule update --remote
  - brew install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
  - cd Example

before_script:
  - carthage bootstrap --no-use-binaries --platform iOS
  
script:
  - xcodebuild -project $PROJECT_NAME -scheme $PROJECT_SCHEME -sdk iphonesimulator test -parallelizeTargets | xcpretty -c && test ${PIPESTATUS[0]} -eq 0

after_failure:
  - cat $TMPDIR/carthage-*.log