
before_install:
  - gem update --system
  - gem install bundler# Configuration
language: objective-c
osx_image: xcode10.2
xcode_sdk: iphonesimulator11.0
# Continuous Integration Script
#   fastlane scan - runs the application tests
script:
- fastlane scan
- fasltane jazzy