efault_platform(:ios)

platform :ios do


############################## PRE ##############################

before_all do

  #ensure_git_status_clean

end

############################## Lanes #############################
lane :test do
  scan()
end

